name: Create Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'  # matches 1.2.3
      - '[0-9]+.[0-9]+'         # matches 1.0
      - '[0-9]+'                # matches 1

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed for creating releases
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history and tags

      - name: Get repository and tag info
        id: info
        run: |
          echo "repo_name=${GITHUB_REPOSITORY#*/}" >> $GITHUB_OUTPUT
          echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Validate version format
        run: |
          if ! [[ "${{ steps.info.outputs.tag }}" =~ ^[0-9]+(\.[0-9]+){0,2}$ ]]; then
            echo "Invalid version format: ${{ steps.info.outputs.tag }}"
            echo "Version must be in the format: 1 or 1.0 or 1.0.0"
            exit 1
          fi

      - name: Create zip file
        run: |
          zip -r "${{ steps.info.outputs.repo_name }}_${{ steps.info.outputs.tag }}.zip" . \
            -x "*.git*" \
            -x "*.github*" \
            -x "*.gitignore" \
            -x "README.md" \
            -x "LICENSE"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.info.outputs.repo_name }}_${{ steps.info.outputs.tag }}.zip
          draft: false
          prerelease: false
          fail_on_unmatched_files: true
          generate_release_notes: true
